### ISSUE TITLE
FALCOSIDEKICK_UI_TTL 

### ISSUE THREAD

**Issue by mugambika** [falcosecurity/falcosidekick-ui#101]
**What to document**

I would like to understand what is FALCOSIDEKICK_UI_TTL used for. How does it help in Redis database not getting filled ?
Does it consider the number of events or number of days ?

If there are a lot of events, how can I limit them by the number of days in UI?

**Comment by Issif** [comment]
This setting sets an expiration (in seconds) for the keys in the Redis database. This is basically this command: https://redis.io/commands/expire/

By setting a value different from zero, the keys will be purged when the ttl expires. For example, with `FALCOSIDEKICK_UI_TTL=84600`, the keys will disappear after 24h.

**Comment by Issif** [comment]
It seems to be an issue with the parsing of flags. I'll take a look next week (not before Wednesday or Thursday)

**Comment by Issif** [comment]
I'm not able to replicate your issue:
```shell
❯ go run .  -t 1209600
2023/07/11 20:47:31 [INFO] : Falcosidekick UI is listening on 0.0.0.0:2802
2023/07/11 20:47:31 [INFO] : log level is info
```

I added a function to export the config and the TTL is correctly parsed and interpreted:
```shell
❯ go run .  -t 1209600
{"listen-address":"0.0.0.0","listen-port":2802,"redis-server":"localhost:6379","dev-mode":false,"disable-auth":false,"log-level":"info","ttl":1209600,"credentials":"admin:admin"}
2023/07/11 20:48:30 [INFO] : Falcosidekick UI is listening on 0.0.0.0:2802
2023/07/11 20:48:30 [INFO] : log level is info
```

Same with the env var.

**Comment by Issif** [comment]
FYI #108
