### ISSUE TITLE
Add sign-in with GitHub

### ISSUE THREAD

**Issue by 123MwanjeMike** [falcosecurity/falcosidekick-ui#102]
**Motivation**
 We have many users in a GitHub organisation who need to access Falco. Even though it's still possible to do so through username and password. It'd be easier for users to simply log in with their GitHub accounts instead and that way we don't have to make them remember passwords.

**Feature**

- Is it also possible to incorporate other authentication methods such as log in with GitHub aside from the default username and password?

**Alternatives**

- Keep using username and password

**Additional context**

**Comment by Issif** [comment]
The next version of falcosidekick-ui will allow to disable the basic auth. I'm not ready to add more complex authentication mechanisms for now, my idea since the beginning was to let the users set up something more robust, a real ingress proxy (nginx-ingress, traefik, ...)

**Comment by 123MwanjeMike** [comment]
Thanks @Issif 
That makes sense
