### ISSUE TITLE
UI access failed

### ISSUE THREAD

**Issue by KangYingjie0** [falcosecurity/falcosidekick-ui#104]
os: ubuntu18.04.6
falco: 0.35.1
falcosidekick: 2.27.0
falcosidekick-ui: v2.1.0

I deployed falco+falcosidekick+falcosidekick-ui+redis on ubuntu. 
But when I access http://localhost:2802/, it outputs {"message":"Not Found"}. Then I tried /ui and /dashboard, they output the same message.
I can trace falco events from redis. 
I can successfully access /docs and most API interfaces ( except /api/v1 and /api/v1/authenticate ).

Would you give me some hints? Thank you.

**Comment by KangYingjie0** [comment]
I encountered the problem when I deployed it directly on the host. Now I have deployed it in docker, and the problem doesn't occur again.

**Comment by Issif** [comment]
It makes sense.
