### ISSUE TITLE
Migrate circleci jobs to GHA

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falcosidekick-ui#109]
**Motivation**

We're in the process of dismissing CircleCI in favor of GitHub Actions. Most repos already migrated.

**Feature**

Port these jobs to GitHub Actions
https://github.com/falcosecurity/falcosidekick-ui/blob/master/.circleci/config.yml

**Alternatives**

**Additional context**

**Comment by leogr** [comment]
cc @falcosecurity/falcosidekick-ui-maintainers

**Comment by Issif** [comment]
I'll work on that next week.

**Comment by Issif** [comment]
It's done since #112 :+1:
