### ISSUE TITLE
Syntax error at offset

### ISSUE THREAD

**Issue by ctdfo** [falcosecurity/falcosidekick-ui#143]
**Describe the bug**
We are getting the error `Syntax error at offset` in our logs. The occurs when any special character of `,.<>{}[]"':;!@#$%^&*()+=~` is added to the `Search` bar of the `Events` section in the UI.

**How to reproduce it**
Install the Falco Helm chart with Falcosidekick (using version `4.3.0`, which corresponds to app version `0.37.1`) and search for an event (with any of the following special character: `,.<>{}[]"':;!@#$%^&*()+=~`) in the `Search` bar of the `Events` section.

**Expected behaviour**
No `Syntax error at offset` when special characters `,.<>{}[]"':;!@#$%^&*()+=~` is added to the `Search` bar of the `Events` section in the UI.

**Screenshots**
When I search for the event time `06:47:14:398`, that has the special character `:`, I get the error:
![image](https://github.com/falcosecurity/falcosidekick-ui/assets/140103998/44d1bb05-233c-4478-9a0d-c32b4e8e8454)
![image](https://github.com/falcosecurity/falcosidekick-ui/assets/140103998/e76c1831-1e16-4f9a-be0e-0f0405a2b6cb)

But then when I properly escape the `:` using `\` (i.e., `06\:47\:14\:398`), I don't get the error:
![image](https://github.com/falcosecurity/falcosidekick-ui/assets/140103998/81179369-9d7a-425c-9af8-b7c8796e922d)

**Environment**

- Falco version:
0.37.1

- System info:
Linux version 5.15.148.2-2.cm2 (root@CBL-Mariner) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Fri Feb 23 23:44:30 UTC 2024

- Cloud provider or hardware configuration:
AKS
- OS:
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.10
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
/app $ 

- Kernel:
Linux falco-falcosidekick-ui-5f89b8bc9d-zn869 5.15.148.2-2.cm2 #1 SMP Fri Feb 23 23:44:30 UTC 2024 x86_64 Linux

- Installation method:
Kubernetes

**Additional context**
I believe the issue occurs with the API call `/api/v1/events/count/:groupby` that calls the `CountBy` function, then the `CountKeyBy` function, then the `newQuery` function that calls the erroneous [`Escape` function](https://github.com/falcosecurity/falcosidekick-ui/blob/69cff81e4de7/internal/utils/utils.go#L168) that doesn’t escape all punctuation correctly (see screenshot below). The function correctly escapes hyphens (with the use of a single backslash), but then incorrectly escapes forward slashes and periods by using two backslashes (and omits all other special characters). This is why when we put one of those characters in the search field, we get the error.
![image](https://github.com/falcosecurity/falcosidekick-ui/assets/140103998/0208c564-bc7a-4524-b884-d5634e5ce82c)

In Redis, when you query for tags that contain punctuation, you must escape that punctuation with a backslash character (\). If not, then you’ll get the error we are seeing (see: https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/tags/ and https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/escaping/).

**Comment by Issif** [comment]
Thanks for this report, I'll replace the escape function to handle more characters. FYI, I didn't use the Redis TAGS for the values.

**Comment by Issif** [comment]
The PR #145 fixes that issue, it will be included in the next release. The ETA is before summer.

**Comment by sanchaytata** [comment]
Hi @ctdfo / @Issif ,
After receiving an event in the falco sidekick UI, it is automatically disappearing after a few minutes, In the logs i can see the below message,

```
echo: http: panic serving 10.0.60.110:38806: interface conversion: interface {} is []string, not string
goroutine 357 [running]:
net/http.(*conn).serve.func1()
        $GOROOT/src/net/http/server.go:1854 +0xbf
panic({0x9c8c00, 0xc00069bc20})
        $GOROOT/src/runtime/panic.go:890 +0x263
github.com/falcosecurity/falcosidekick-ui/internal/database/redis.CountKeyBy(0x0?, 0xc0002d4b40)
        /home/runner/work/falcosidekick-ui/falcosidekick-ui/internal/database/redis/count.go:49 +0x89f
github.com/falcosecurity/falcosidekick-ui/internal/events.CountBy(0xa58424?)
        /home/runner/work/falcosidekick-ui/falcosidekick-ui/internal/events/count.go:24 +0x4a
github.com/falcosecurity/falcosidekick-ui/internal/api.CountByEvent({0x137d458, 0xc0002d4a00})
        /home/runner/work/falcosidekick-ui/falcosidekick-ui/internal/api/api.go:98 +0x1f6
github.com/labstack/echo/v4/middleware.BasicAuthWithConfig.func1.1({0x137d458, 0xc0002d4a00})
        pkg/mod/github.com/labstack/echo/v4@v4.11.1/middleware/basic_auth.go:93 +0x42a
github.com/labstack/echo/v4.(*Echo).add.func1({0x137d458, 0xc0002d4a00})
        pkg/mod/github.com/labstack/echo/v4@v4.11.1/echo.go:582 +0x51
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000610240, {0x1374920?, 0xc0005481c0}, 0xc000542400)
        pkg/mod/github.com/labstack/echo/v4@v4.11.1/echo.go:669 +0x3d1
net/http.serverHandler.ServeHTTP({0xc0004c1170?}, {0x1374920, 0xc0005481c0}, 0xc000542400)
        $GOROOT/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0004e6cf0, {0x1374d88, 0xc00060d950})
        $GOROOT/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        $GOROOT/src/net/http/server.go:3089 +0x5ed
```

Can you please help me why this is happening

Cloud provider or hardware configuration: AKS
Installation method: helm
