### ISSUE TITLE
WebUI answers with {"message":"Not Found"}

### ISSUE THREAD

**Issue by m8522s** [falcosecurity/falcosidekick-ui#149]
We I go the web address of a running `falcosidekick-ui`, the browser receives `{"message":"Not Found"}` instead of the HTML-based web page.
URL: http://localhost:2802/

This issue happens on falcosidekick-ui version 2.2.0. I also tested with 2.3.0-rc3 and 2.1.0 with the same result.

falcosidekick-ui is started with: `falcosidekick-ui -l debug`
I used the binary version from `falcosidekick-ui_2.2.0_linux_arm64.tar.gz`

The console messages show, that the process is running ans receiving events from `falcosidekick`:
```
2024/07/15 13:30:35 [WARN] : Auhentication disabled
2024/07/15 13:30:35 [INFO] : Falcosidekick UI is listening on 0.0.0.0:2802
2024/07/15 13:30:35 [INFO] : log level is debug
2024/07/15 13:32:38  NEW event 'event:79b4e17d-63dd-435d-9d16-cf55a1d93867'
```

Falcosidekick-ui is running on a Raspberry Pi 3B+ with Raspberry Pi OS (Debian 12.6)

**Describe the bug**
The documentation at https://github.com/falcosecurity/falcosidekick-ui#ui does not work for my set up. The web UI is not visible and the browser shows `{"message":"Not Found"}`.
Other endpoints, like `/docs` and `/api/v1/`, are working as expected.

**How to reproduce it**
Start `falcosidekick-ui` and run `curl http://localhost:2802/`

**Expected behaviour**
I expect a web page similar to the screenshot on your GitHub page at https://github.com/falcosecurity/falcosidekick-ui#screenshots

**Screenshots**
n/a

**Environment**

- Falco version:
Mon Jul 15 18:19:47 2024: Falco version: 0.38.1 (aarch64)
Mon Jul 15 18:19:47 2024: Falco initialized with configuration files:
Mon Jul 15 18:19:47 2024:    /etc/falco/falco.yaml
Mon Jul 15 18:19:47 2024: System info: Linux version 6.6.31+rpt-rpi-v8 (serge@raspberrypi.com) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29)
{"default_driver_version":"7.2.0+driver","driver_api_version":"8.0.0","driver_schema_version":"2.0.0","engine_version":"40","engine_version_semver":"0.40.0","falco_version":"0.38.1","libs_version":"0.17.2","plugin_api_version":"3.6.0"}

- System info:
{
  "machine": "aarch64",
  "nodename": "raspberrypi",
  "release": "6.6.31+rpt-rpi-v8",
  "sysname": "Linux",
  "version": "#1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29)"
}

- Cloud provider or hardware configuration:
Raspberry Pi 3B+

- OS:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel:
Linux raspberrypi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

- Installation method:
Falco from: falco-0.38.1-aarch64.deb
Falcosidekick from falcosidekick_2.29.0_linux_arm64.tar.gz
Falcosidekick-UI from falcosidekick-ui_2.2.0_linux_arm64.tar.gz

**Comment by Issif** [comment]
Hi,

There are issues on arm I still can't explain, see #95. I'm planning to rewrite (once again) the UI in the next months, I hope the new stack will work better.
