### ISSUE TITLE
Kubernetes Installation for falcosidekick-ui

### ISSUE THREAD

**Issue by manas-suleman** [falcosecurity/falcosidekick-ui#156]
I've installed falco and falcosidekick on kubernetes and was planning on deploying falcosidekick-ui on it. But I couldn't find any documentation describing falcosidekick-ui deployment in kubernetes system so I'm assuming that's not supported. Please let me know if that's not the case. Otherwise, can we please have falcosidekick-ui deployment guide for kubernetes?

Thanks

**Comment by manas-suleman** [comment]
@Issif thanks for your reply. I installed falcosidekick as a dependency to falco as described here https://github.com/falcosecurity/falcosidekick?tab=readme-ov-file#in-kubernetes. I've just realized there's a `falcosidekick.webui.enabled=true` option to enable ui as described here https://github.com/falcosecurity/charts/tree/master/charts/falco#values. It's not explained in the values table https://github.com/falcosecurity/charts/tree/master/charts/falco#values so missed it earlier.

Thanks for pointing me to the right direction.

**Comment by Issif** [comment]
Because falcosidekick is a dep, the values are not listed in the readme for the falco chart but in the one for sidekick: https://github.com/falcosecurity/charts/tree/master/charts/falcosidekick#values
