### ISSUE TITLE
Feature Request: sort by time frame

### ISSUE THREAD

**Issue by jonny-wg2** [falcosecurity/falcosidekick-ui#16]
**Motivation**

Ability to easily parse the alerts.

**Feature**

Ability to sort events based on a time by clicking a button.
e.g.
last 1 hour
last 6 hours
last 12 hours
last 24 hours
last 3 days
last 7 days

**Alternatives**

n/a 

**Additional context**

Similar feature could be found in kibana for example.

**Comment by Issif** [comment]
Hello @jonny-wg2,

Thanks for your issue.

For now, the UI is really "simple", no database, last events are stored in pod memory and only the last 50s (you can change this with `-r` arg).

I understand your need, but for improved statistics, I encourage people to use a different output (elasticsearch works really well for).

My idea when I started this project was to propose a UI for an easy onboarding and have results in real time in any cluster, without setting up a real backend.

We'll see how things will evolve. If more and more people wants new features but I don't want to overlap with Sysdig Secure.

wdyt @fjogeleit ?

**Comment by fjogeleit** [comment]
A basic filter is no big deal but you're right that the UI does not persist any event. You could only filter whats "in memory".

**Comment by Issif** [comment]
> A basic filter is no big deal but you're right that the UI does not persist any event. You could only filter whats "in memory".

Ok with that, I'll do some test to check memory footprint of event and see how we could store without consuming too much
