### ISSUE TITLE
Frontend is using localhost instead of correct endpoint

### ISSUE THREAD

**Issue by nicotruc** [falcosecurity/falcosidekick-ui#50]
Hi,
There is 2 trouble which prevent using the UI from cluster. 

Requests from website are redirected to localhost, which is not the case when deploying in cluster
https://github.com/falcosecurity/falcosidekick-ui/blob/bb91823f57e999162af11be794f56098a4b041c1/frontend/src/http.js#L9

Then, we have the same problem in documentation :
https://github.com/falcosecurity/falcosidekick-ui/blob/bb91823f57e999162af11be794f56098a4b041c1/docs/docs.go#L529

**Comment by Issif** [comment]
Hi,

What do you mean by "from cluster"? Can you explain me more how you installed the UI, please.

**Comment by nicotruc** [comment]
Well, I installed it through the Helm chart, that I had to adjust so it fit to my openshift cluster (creating a SCC and a route so there is an endpoint to the service)

Then I can access to the platform from my pc, API is also working by referring the endpoint url, but when using the frontend, I'm unable to view anything because the frontend is looking up to localhost:2802 for each of its requests

**Comment by Issif** [comment]
Ok, I works with a port forward because we use "localhost", but not for NodePort or Ingress. We'll fix it. Thanks.

**Comment by epcim** [comment]
confirm, 
k8s: port-forward works, it does not work behind traefik ingress:

```
                traefik.ingress.kubernetes.io/preserve-host: "true"
                ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
```
UI console still goes to

``` xhr.js:210          GET http://localhost:2802/api
```
