### ISSUE TITLE
Add config for redis data expiration

### ISSUE THREAD

**Issue by jefimm** [falcosecurity/falcosidekick-ui#54]
Currently writing data to redis does not set any TTL on the data  - this will eventually fill the disk
Please add configuration for the expiration of the data written to redis with default of no expiration

**Comment by Issif** [comment]
Good point. I will add it. Thanks

**Comment by Issif** [comment]
I dug to add this feature, and for now, it's not possible. The module I use for communication with redisearch is `https://github.com/RediSearch/redisearch-go` (official SDK) and it doesn't allow to send an `FT.EXPIRE` command to set a ttl.
I think it's not a big deal to submit a PR for adding this feature in the SDK but I don't know how long it will take before the maintainers release a new version.

**Comment by jefimm** [comment]
I have installed falco + falcosidekick-ui on our test cluster before tuning and adjusting rules and it run out of 1GB **disk** space in less than a week. This is the reason for this request.

**Comment by Issif** [comment]
How many events did you get for 1GB? I get your point, it's a really valuable idea and I would like to implement the feature, but the SDK doesn't allow it, here's the function they use to add keys [https://github.com/RediSearch/redisearch-go/blob/bd32e0b428fd340ac1bc71812e9e9dcdcc852e52/redisearch/query.go#L417](https://github.com/RediSearch/redisearch-go/blob/bd32e0b428fd340ac1bc71812e9e9dcdcc852e52/redisearch)/query.go#L417

**Comment by jefimm** [comment]
maybe this would help https://stackoverflow.com/questions/66028975/how-to-set-a-key-with-expiry-using-redisgo-api

**Comment by RBGauravJoshi** [comment]
@Issif How to use this setting when setting up sidekick-ui with helm chart? Is there a "ttl" field which can be set inside values.yaml?

**Comment by Issif** [comment]
The helm chart is not ready as this feature will be in next falcosidekick-ui release. But yes, an helm value will expose it.
