### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by adnankobir** [falcosecurity/falcosidekick-ui#64]
**Motivation**

The UI is lacking any form of authentication. Given that there might be sensitive data, the UI should implement some form of authentication - preferably SSO.  

**Feature**

User auth or SSO-based authentication.

**Alternatives**

**Additional context**

**Comment by RBGauravJoshi** [comment]
+1 for this feature!

**Comment by praveenjindal62** [comment]
Is there a way to disable the basic authentication ?

**Comment by Issif** [comment]
The last release v2.1.0 brings a basic auth, I will see if add more in future

**Comment by Issif** [comment]
> Is there a way to disable the basic authentication ?

Not, the default credentials are admin/admin
