### ISSUE TITLE
base path (subpath) configuration

### ISSUE THREAD

**Issue by simion** [falcosecurity/falcosidekick-ui#65]
We need to be able to serve falconsidekick-ui under our-domain.com/subpath 

Right now it's not possible to configure a sub-directory to be served.
Even if we use regex + rewrite for ingress, the js/css ressources are served under root path, so it's impossible to make it work. 

Thanks :)

**Comment by Issif** [comment]
We'll take a look asap

**Comment by trallnag** [comment]
As falcosidekick-ui is using Echo, we can use a configurable `e.Group(config.base)` before adding any handlers or subgroups. But it is more difficult to customize subpath for frontend code I think

**Comment by Issif** [comment]
> As falcosidekick-ui is using Echo, we can use a configurable `e.Group(config.base)` before adding any handlers or subgroups. But it is more difficult to customize subpath for frontend code I think

Exactly, on Echo's side, I did easily, but for the frontend I wasn't able to have something useful, this is why I post poned this feature to next release

**Comment by trallnag** [comment]
I managed to serve it under hardcoded subpath in #84.

**Comment by gaprop** [comment]
I'm running into the same issue.

**Comment by jgmartinez** [comment]
I'm facing the same issue and I've been debugging it a bit. It seems that VUE Webpack allows to set the ASSET_PATH environment variable to specify the public path for the assets https://webpack.js.org/guides/public-path/

I've set the env in my container with no luck.

**Comment by fjogeleit** [comment]
Environment variables needs to be set on build time, not on runtime. So they have no effect if the frontend is already builded.
