### ISSUE TITLE
Add support for ARM

### ISSUE THREAD

**Issue by e-minguez** [falcosecurity/falcosidekick-ui#66]
**Motivation**

As Falco supports ARM, I guess it would be nice for sidekick-ui to support ARM as well.

**Feature**

Support ARM CPUs

**Alternatives**

Use sidekick with no UI

**Additional context**

**Comment by Issif** [comment]
Falcosidekick now relies on Redisearch module, I know Redis itself works on arm64, I'm not 100% it will be for Redisearch. At least, the official Docker image doesn't bring any arm64 flavor.

**Comment by Issif** [comment]
I propose to change the redis docker image, an arm one is available https://github.com/falcosecurity/charts/pull/467

**Comment by e-minguez** [comment]
Does this https://kubernetes.slack.com/archives/CMWH3EH32/p1678925634261929?thread_ts=1678862299.535779&cid=CMWH3EH32 mean that this issue can be closed?

**Comment by Issif** [comment]
Yes 👍

**Comment by e-minguez** [comment]
Let's close it then! :)
