### ISSUE TITLE
Add possibility to set loglevel

### ISSUE THREAD

**Issue by ArgTang** [falcosecurity/falcosidekick-ui#68]
**Motivation**

We are seing mostly 2022/09/29 14:16:20 [INFO] : NEW event 'event:1664460980729338' logs from sidekick ui.
It would be great to be able to have a flag to set the loglevel to warn in production

**Feature**
Add flag/environment variable to enable setting loglevel at runtime

**Comment by Issif** [comment]
Good idea. I'll work on that. Thanks
