### ISSUE TITLE
Opt-out of authorization / Disable login / Disable authorization

### ISSUE THREAD

**Issue by trallnag** [falcosecurity/falcosidekick-ui#85]
**Motivation**

In some scenarios the authorization is redundant.

1. UI is only accessed by admins via port forwarding. In this case we don't need extra authorization, because only admins have access to service.
2. UI is hosted behind domain and in front of service is a gateway that handles authorization. Again we don't need additional login.

**Feature**

Opt-out of authorization.

If that is not possible maybe accept credentials in headers? Then one could solve usecase 2 by hardcoding credentials in gateway configuration.

**Comment by Issif** [comment]
1. Yes and No. In this case, except if you have some Network Policies or a Service Mesh, the API of falcosidekick-ui is accessible from any pod in your cluster. Even the frontend with a proxyfying/tunneling is.
2. I agree it's an issue for users with a proxy, this is why I'm planning to add the option to disable the login in next release.

Right now, the authentication mechanism is just a Basic Auth, so you can use the `Authorization` header as well:
```
Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l
``` 
With `YWxhZGRpbjpvcGVuc2VzYW1l` the credentials `admin:password` base64 encoded. [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic_authentication)

**Comment by alex0ptr** [comment]
@Issif Is this actually working? We also have strong auth as part of our ingress and given this comment I thought it would be an easy fix if we set a header in there.

I confidently added

```yaml
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization "Basic YWRtaW46YWRtaW4=";
```

to https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml#L866

However it is still redirecting me to a login page.

Inspecting the code (I'm not very familiar with vue) I see that the frontend will route to the login page whenever the credentials [are not in the state](https://github.com/falcosecurity/falcosidekick-ui/commit/fc108211125db624367b5b2e9fde4acc0d028ef4#diff-2766750fe4e47e725d24427092ed92a78eca3bae6c3583646f0ce4228ae872f8R56). `setCredentials` seems only ever be called [from the login page](https://github.com/falcosecurity/falcosidekick-ui/commit/fc108211125db624367b5b2e9fde4acc0d028ef4#diff-827b1772eb33cab4253e982c2074946aab08737406567d737c4d2434feeeb184R79). Shouldn't be there another call whenever the application loads in order for the header to be written to the state before the router thingy?

**Comment by dmolik** [comment]
I just hit this, can we get a new container tag?

**Comment by Issif** [comment]
I crafted a pre-release image for you https://hub.docker.com/layers/falcosecurity/falcosidekick-ui/v2.2.0-rc1/images/sha256-d80b0c8bf9e8307dec78c33e85eb43225dfabf2518622b20111269c3bfc9ddf4?context=explore

**Comment by sanchaysaxena** [comment]
Hi @alex0ptr,

I am still facing the same issue, i am using the oauth2 proxy and it is redirecting me to login page even after disabling the auth. were you able to overcome this issue?

**Comment by alex0ptr** [comment]
I think the fix is in the PR: https://github.com/falcosecurity/falcosidekick-ui/pull/91/commits/96826d8392f486571d306f59795cabf9cd88db15#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23
