### ISSUE TITLE
query does not support "-" well

### ISSUE THREAD

**Issue by etazhou** [falcosecurity/falcosidekick-ui#90]
**Describe the bug**
I use falcosidekick-ui:v2.1.0 and falcosidekick:2.27.0, I found below issues
1.  drop down list of "hostnames" can not list anything.
2.  in the "search" part,  when I wrote "123", it works find,  but when I wrote "node-10" , it show nothing

**How to reproduce it**

**Expected behaviour**

**Screenshots**

![图片](https://user-images.githubusercontent.com/31144779/225249166-0ea6e9c5-8e19-435a-808b-d6ced6140939.png)
![图片](https://user-images.githubusercontent.com/31144779/225249283-884da74b-2ca2-41f7-bcfb-2c54aa872158.png)
![图片](https://user-images.githubusercontent.com/31144779/225249378-bc585866-6217-40e3-9f33-1dafc49644ae.png)

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Issif** [comment]
thanks, I'll see if I can fix that.

**Comment by etazhou** [comment]
Hi,  Lssif
  is there any update for this issue?  We expect this issue can be fixed soon , thanks.

**Comment by Issif** [comment]
It's in my todo for this week. I don't have any ETA for the next release btw.

**Comment by etazhou** [comment]
thanks for the info.

**Comment by Issif** [comment]
I found a fix, it works for new events, not previous.

![image](https://user-images.githubusercontent.com/4520100/228816471-526bb2bc-6b9d-46c8-9f1c-d167b3386df8.png)

FYI, the issue is on redisearch's side, the tokenization splits strings with a `-` ([source](https://redis.io/docs/stack/search/reference/escaping/)), I had to escape the documents and queries.

**Comment by etazhou** [comment]
thanks for your excelletent support.  I will try it when code merged.

**Comment by etazhou** [comment]
sorry  but seems code still not be merged to master.  Any plan for that?

**Comment by Issif** [comment]
> sorry but seems code still not be merged to master. Any plan for that?

I has been into master, Not in a release yet but `:latest` tag for the image should work.
